# This is for the production environment
services:
  frontend:
    platform: linux/amd64
    build:
      context: ./services/node
      dockerfile: Dockerfile
    command: "npm start"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-backend-network

  backend:
    platform: linux/amd64
    build:
      context: ./services/php
      dockerfile: Dockerfile
    command: "php-fpm"
    environment:
      - APP_ENV=production
    networks:
      - frontend-backend-network

  frontend-proxy:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./services/nginx/nginx.frontend.prod.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - frontend-backend-network

  backend-proxy:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./services/nginx/nginx.backend.prod.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - frontend-backend-network

networks:
  frontend-backend-network:
