# This is for the local development environment
services:
  frontend:
    platform: linux/amd64
    build:
      context: ./services/node
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../frontend
        target: /app
    command: "npm run dev"
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - frontend-backend-network

  backend:
    platform: linux/amd64
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ../backend
        target: /var/www
    command: "php-fpm"
    environment:
      - APP_ENV=development
    ports:
      - "9000:9000"
    networks:
      - frontend-backend-network

  nginx-frontend:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./services/nginx/nginx.frontend.dev.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - frontend-backend-network

  nginx-backend:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: ./services/nginx/nginx.backend.dev.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - frontend-backend-network

networks:
  frontend-backend-network:
