# This is for the local development environment
services:
  frontend:
    container_name: frontend
    tty: true
    build:
      context: ./services/node
      dockerfile: Dockerfile-development
      args:
        - NODE_VERSION=${NODE_VERSION}
        - FRONTEND_WORKDIR=${FRONTEND_WORKDIR}
    volumes:
      - type: bind
        source: ${FRONTEND_SRC_DIR}
        target: ${FRONTEND_TGT_DIR}
    environment:
      TZ: Asia/Tokyo
      WATCHPACK_POLLING: true
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000

  backend:
    container_name: backend
    build:
      context: ./services/php
      dockerfile: Dockerfile-development
      args:
        - PHP_VERSION=${PHP_VERSION}
        - BACKEND_WORKDIR=${BACKEND_WORKDIR}
    volumes:
      - type: bind
        source: ${BACKEND_SRC_DIR}
        target: ${BACKEND_TGT_DIR}
    depends_on:
      - mysql

  frontend-proxy:
    container_name: frontend-proxy
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./services/nginx/nginx.frontend.dev.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

  backend-proxy:
    container_name: backend-proxy
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./services/nginx/nginx.backend.dev.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  mysql:
    container_name: mysql
    build:
      context: ./services/mysql
      dockerfile: Dockerfile-development
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1

volumes:
  db-store:

networks:
  frontend-backend-network:
    # ネットワーク名を明示的に設定
    name: frontend-backend-network
    driver: bridge
