# This is for the local development environment (override)
services:
  frontend:
    platform: linux/amd64
    ports:
      - 3000:3000

  backend:
    platform: linux/amd64
    ports:
      - 9000:9000

  frontend-proxy:
    platform: linux/amd64
    ports:
      - 80:80

  backend-proxy:
    platform: linux/amd64
    ports:
      - 8000:80

  mysql:
    platform: linux/amd64
    ports:
      - 3306:3306

  mailhog:
    platform: linux/amd64
    ports:
      - 8025:8025
